### ISSUE TITLE
Help with map!

### ISSUE THREAD

**Issue by CarvenSi** [vintagesucks/PokemonGo-Map-Install-Guides#1]
What login I need to write into command? gmail? Ok! And why if I change coordinats in command ,place on map don't change? Sry for my english! Help pls! :D And I don't pokemons on map! D:

**Comment by vintagesucks** [comment]
Please open an issue here if you're having problems with the map and not with this guide: 
- https://github.com/AHAAAAAAA/PokemonGo-Map
